//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDictionaryCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataDictionaryCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Finished setting key descriptions 的當地語系化字串。
        /// </summary>
        internal static string AdvancedSettingsKeyDescriptonsEndAction {
            get {
                return ResourceManager.GetString("AdvancedSettingsKeyDescriptonsEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting descriptions 的當地語系化字串。
        /// </summary>
        internal static string AdvanceSettingsKeyDescriptionsBeginAction {
            get {
                return ResourceManager.GetString("AdvanceSettingsKeyDescriptionsBeginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data Dictionary Creator {0} 的當地語系化字串。
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The application has been updated and will now restart. 的當地語系化字串。
        /// </summary>
        internal static string ApplicationUpdated {
            get {
                return ResourceManager.GetString("ApplicationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A login with DBO permission is required. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionErrorDBORequired {
            get {
                return ResourceManager.GetString("ConnectionErrorDBORequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Database connection failed. See Connect To Database tab for details. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionErrorGeneric {
            get {
                return ResourceManager.GetString("ConnectionErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Your database connection failed. Please try again. You may use the connection string builder by clicking the ellipse to the right. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionErrorGenericDetailed {
            get {
                return ResourceManager.GetString("ConnectionErrorGenericDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please provide values for table descriptions and additional properties using the grid and tools below. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionInstructionsConnected {
            get {
                return ResourceManager.GetString("ConnectionInstructionsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No valid database connection has been established.  Visit the Connect to Database tab to continue. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionInstructionsNotConnected {
            get {
                return ResourceManager.GetString("ConnectionInstructionsNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You are not currently connected. Please specify a database to document. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionNotConnected {
            get {
                return ResourceManager.GetString("ConnectionNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You are currently connected to {0}/{1}. You may immediately begin documenting the database, but advanced settings may faciliate the process.  We suggest you visit this tab first. 的當地語系化字串。
        /// </summary>
        internal static string ConnectionSuccessGeneric {
            get {
                return ResourceManager.GetString("ConnectionSuccessGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot install the latest version of the application. \r\nPlease check your network connection, or try again later. Error: {0} 的當地語系化字串。
        /// </summary>
        internal static string DeploymentDownloadExceptionMessage {
            get {
                return ResourceManager.GetString("DeploymentDownloadExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting up for documentation. 的當地語系化字串。
        /// </summary>
        internal static string DocumentationSetupBeginAction {
            get {
                return ResourceManager.GetString("DocumentationSetupBeginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading table. 的當地語系化字串。
        /// </summary>
        internal static string DocumentLoadTableBeginAction {
            get {
                return ResourceManager.GetString("DocumentLoadTableBeginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Table load completed. 的當地語系化字串。
        /// </summary>
        internal static string DocumentLoadTableEndAction {
            get {
                return ResourceManager.GetString("DocumentLoadTableEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 276 的當地語系化字串。
        /// </summary>
        internal static string DocumentMaxGridHeight {
            get {
                return ResourceManager.GetString("DocumentMaxGridHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Document setup complete. 的當地語系化字串。
        /// </summary>
        internal static string DocumentSetupEndAction {
            get {
                return ResourceManager.GetString("DocumentSetupEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Completed export 的當地語系化字串。
        /// </summary>
        internal static string ExportEndAction {
            get {
                return ResourceManager.GetString("ExportEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Got an error starting the program.  There might be no system default for this file type. 的當地語系化字串。
        /// </summary>
        internal static string ExportErrorGeneric {
            get {
                return ResourceManager.GetString("ExportErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Completed import. 的當地語系化字串。
        /// </summary>
        internal static string ImportEndAction {
            get {
                return ResourceManager.GetString("ImportEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to validate script as a valid export script. 的當地語系化字串。
        /// </summary>
        internal static string ImportErrorCanNotValidateScript {
            get {
                return ResourceManager.GetString("ImportErrorCanNotValidateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Import file was not exported by a current version of this program. 的當地語系化字串。
        /// </summary>
        internal static string ImportErrorUnsupportedVersion {
            get {
                return ResourceManager.GetString("ImportErrorUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Column {0}.[{1}] does not exist. 的當地語系化字串。
        /// </summary>
        internal static string MissingColumnException {
            get {
                return ResourceManager.GetString("MissingColumnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Table {0} does not exist. 的當地語系化字串。
        /// </summary>
        internal static string MissingTableException {
            get {
                return ResourceManager.GetString("MissingTableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A required update is available, which will be installed now. 的當地語系化字串。
        /// </summary>
        internal static string RequiredUpdateAvailable {
            get {
                return ResourceManager.GetString("RequiredUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting table description. 的當地語系化字串。
        /// </summary>
        internal static string TableDescriptionBeginAction {
            get {
                return ResourceManager.GetString("TableDescriptionBeginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Table description set. 的當地語系化字串。
        /// </summary>
        internal static string TableDescriptionEndAction {
            get {
                return ResourceManager.GetString("TableDescriptionEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Would you like to update the application now? 的當地語系化字串。
        /// </summary>
        internal static string UpdateApplicationNow {
            get {
                return ResourceManager.GetString("UpdateApplicationNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Available 的當地語系化字串。
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
    }
}
